[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "arches-bng"
description = "An Arches extension app providing support for functionality relating to the British National Grid (BNG) coordinate system."
readme = "README.md"
version = "1.0.0"
license = {text = "GNU AGPL3"}
authors = []
maintainers = [{name = "Historic England", email = "donotreply@historicengland.org.uk"}]
keywords = ["arches", "extension", "django", "heritage", "historic-data", "coordinate-system", "bng", "british-national-grid", "datatype","widget","function","spatial-filter"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
]
requires-python = ">=3.10"
dependencies = [
    "arches>=7.6.22,<7.7.0",
]
[project.urls]
Homepage = "https://github.com/HistoricEngland/arches-bng"
Repository = "https://github.com/HistoricEngland/arches-bng.git"
Issues = "https://github.com/HistoricEngland/arches-bng/issues"
Changelog = "https://github.com/HistoricEngland/arches-bng/releases"

[project.optional-dependencies]
dev = [
    "livereload",
    "sst",
    "coverage",
    "django-silk==5.1.0",
    "pre-commit==3.8.0",
    "black==24.4.2",
]

[tool.setuptools.packages.find]
include = ["arches_bng*"]
exclude = ["arches_bng.logs*"]

[tool.setuptools]
include-package-data = true
